OOD_Project/urls.py
import users.urls
import knowledge.urls

from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$',  RedirectView.as_view(pattern_name='base-view', permanent=True)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include(users.urls)),
    url(r'^knowledge/', include(knowledge.urls)),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
import users.views

urlpatterns = [
    url(r'^login/$', users.views.loginView, name='login'),
    url(r'^logout/$', users.views.logoutAj, name='logout'),
    url(r'^base/$', users.views.baseView, name='base-view'),
    url(r'^register/$', users.views.showRegisterKUser, name='register'),
    url(r'^dismiss/$', users.views.showDismissKUser, name='dismiss'),
    url(r'^change-pass/$', users.views.showChangePass, name='change-pass'),
    url(r'^report-user-activity/$', users.views.showReportUserActivity, name='show-report-user-activity'),
    url(r'^special-privilege-request/$', users.views.showSpecialprivilageRequest, name='show-special-privilege-request'),
    url(r'^request-manager/$', users.views.showRequestManager, name='show-request-manager'),
    url(r'^user-profile/(?P<user_id>\d+)$', users.views.userProfileView, name='show-user-profile'),

    url(r'^search/user/$', users.views.searchUser, name='show-search-user'),
]

knowledge/models.py
from datetime import datetime
import users.models

from django.db import models



def knowledge_file_name(instance, filename):
	return '/'.join(['file', instance.author.user.username, filename])

###################  knowledge  ###################
class Knowledge(models.Model):
	subject = models.CharField(max_length=255)
	source = models.ForeignKey('Source', related_name='knowledge')
	author = models.ForeignKey('users.KUser', related_name='knowledge')
	summary = models.CharField(max_length=255, blank=True, null=True)
	gainWay = models.TextField(blank=True, null=True)
	access = models.IntegerField(default=0)
	createDate = models.DateTimeField(default=datetime.now)

	content = models.TextField(blank=True, null=True)
	file = models.FileField(blank=True, null=True, upload_to=knowledge_file_name)

	def __str__(self):
		return '' + self.subject

	def presentation(self):
		return self.subject

	def rate(self, kuser, vote):
		try:
			rate = Rate.objects.get(knowledge=self, voter=kuser)
		except:
			rate = Rate()
			rate.knowledge = self
			rate.voter = kuser
		rate.up = vote
		rate.save()

	@staticmethod
	def kdelete(id):
		print('remove knowledge :' + repr(id))
		Knowledge.objects.filter(pk=id).delete()


class Rate(models.Model):
	up = models.BooleanField(default=True)
	voter = models.ForeignKey('users.KUser', related_name='rates')
	knowledge = models.ForeignKey('Knowledge', related_name='rates')

	class Meta:
		unique_together = ['voter', 'knowledge']

	def __str__(self):
		return str(self.knowledge) + ' vote ' + ('up' if self.up else 'down') + ' by ' + str(self.voter)


###################  Source  ###################
class Source(models.Model):
	subject = models.CharField(max_length=255, unique=True)
	description = models.TextField()
	createDate = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return self.subject

	def presentation(self):
		return self.subject


class ProjectProces(Source):
	phase = models.CharField(max_length=255)
	startDate = models.DateTimeField()
	endDate = models.DateTimeField()

	def __str__(self):
		return 'ProjectProces: ' + self.phase + '.' + self.subject
		

###################  Tag  ###################
class TagType(models.Model):
	name = models.CharField(max_length=255, unique=True,error_messages={'unique':'نوع برچسب برای این مبحث موجود است.'})

	def __str__(self):
		return '' + self.name

	def presentation(self):
		return self.name


class Tag(models.Model):
	ktype = models.ForeignKey('TagType', related_name='tags')
	knowledge = models.ForeignKey('Knowledge', related_name='tags')

	class Meta:
		unique_together = ['ktype', 'knowledge']

	def __str__(self):
		return 'Tag: (' + self.ktype.name + ') -> ' + self.knowledge.subject

	def abuse_presentation(self):
		return 'برچسب: ' + self.ktype.name + '-' + self.knowledge.subject

	@staticmethod
	def kdelete(id):
		print('remove tag :' + repr(id))
		Tag.objects.filter(pk=id).delete()



###################  Relation  ###################
class InterknowledgeRelationshipType(models.Model):
	name = models.CharField(max_length=255, unique=True,error_messages={'unique':'نوع رابطه برای این مبحث موجود است.'})

	def __str__(self):
		return '' + self.name

	def presentation(self):
		return self.name


class InterknowledgeRelationship(models.Model):
	ktype = models.ForeignKey('InterknowledgeRelationshipType', related_name='relations')
	fromKnowledge = models.ForeignKey('Knowledge', related_name='relationToKnowledge')
	toKnowledge = models.ForeignKey('Knowledge', related_name='relationFromKnowledge')

	class Meta:
		unique_together = ['ktype', 'fromKnowledge', 'toKnowledge']

	def __str__(self):
		return 'InterknowledgeRelationship: (' +self.ktype.name + '( '\
		       + self.fromKnowledge.subject + ' -> ' + self.toKnowledge.subject + ' )'

	def abuse_presentation(self):
		return 'رابطه: ' + self.ktype.name + ' از ' + self.fromKnowledge.subject + ' به ' + self.toKnowledge.subject

	@staticmethod
	def kdelete(id):
		print('remove relation :' + repr(id))
		InterknowledgeRelationship.objects.filter(pk=id).delete()



###################  comment  ###################
class Comment(models.Model):
	author = models.ForeignKey('users.KUser', related_name='comments')
	knowledge = models.ForeignKey('Knowledge', related_name='comments')
	text = models.TextField()
	date = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return 'comment: ' + self.author.user.username + ' on ' + self.knowledge.subject


class KnowledgeUsage(models.Model):
	projectProces = models.ForeignKey('ProjectProces', related_name='usedIn')

	def __str__(self):
		return 'knowledge use: ' + self.author.user.username + ' used ' + self.knowledge.subject + ' in ' + self.projectProces.phase


###################  letter  ###################
# class Letter(models.Model):
# 	subject = models.CharField(max_length=255)
# 	sender = models.CharField(max_length=255)
# 	reciver = models.CharField(max_length=255)
# 	text = models.TextField()
# 	date = models.DateTimeField()

# 	def __str__(self):
# 		return 'letter: ' + self.subject + ' from ' + self.sender + ' to ' + self.reciver

users/models.py
from datetime import datetime

import knowledge.models

from django.db import models
from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth import authenticate


###################  User  ###################
class KUser(models.Model):
	user = models.OneToOneField(User)
	realName = models.CharField(max_length=255)
	job = models.CharField(max_length=255)
	privilege = models.IntegerField()
	# django doesn't support unique error message in forms
	employeeId = models.IntegerField(unique=True, error_messages={'unique':"شماره ی کارمندی تکراریست."})
	isManager = models.BooleanField(choices=((False, 'کاربر'), (True, 'مدیر')), default=False)

	STATE_CHOICES = ((0, 'فعال'),(1, 'غیر فعال'),(2, 'اخراج شده'),)
	state = models.SmallIntegerField(default=0, choices=STATE_CHOICES)

	GENDER_CHOICES = (('M', 'Male'),('F', 'Female'),)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

	def presentation(self):
		return self.user.username

	def __str__(self):
		return ('Manager' if self.isManager else 'User') + ': ' + self.user.username

	def changeJob(self, newJob):
		self.job = newJob
		self.save()

	def fire(self):
		print('dismiss user: ' + self.presentation())
		self.state = 2
		self.user.is_active = False
		self.user.is_staff = False
		self.user.is_superuser = False
		self.user.save()
		self.save()

	def emailPassword(self):
		pass

	def changePassword(self, newPass):
		print('change user pass')
		self.user.set_password(newPass)
		self.user.save()

	def checkPass(self, password):
		user = authenticate(username=self.username, password=password)
		if user is not None:
			return True
		return False




def getKnowledgeUser(usr):
	if isinstance(usr, AnonymousUser):
		return None
	if KUser.objects.filter(user__pk=usr.pk):
		return KUser.objects.get(user__pk=usr.pk)
	return None

def getRequestKUser(request):
	return getKnowledgeUser(request.user)


###################  Log  ###################
class Log(models.Model):
	user = models.ForeignKey('KUser')
	detail = models.TextField()
	createDate = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return 'Log: (' + str(self.createDate) + ') ' + self.user.user.username + ': ' + self.detail

	@staticmethod
	def log_action(request, action):
		usr = getRequestKUser(request)
		log = Log()
		log.user = usr
		log.detail = action
		log.save()

###################  Request  ###################
class KRequest(models.Model):
	user = models.ForeignKey('KUser')
	STATE_CHOICES = ((0, 'برسسی نشده'),(1, 'پذیرفته شده'),(2, 'رد شده'),)
	state = models.IntegerField(default=0, choices=STATE_CHOICES)
	reason = models.TextField(blank=True, null=True)
	url = models.CharField(max_length=255)


	def getReason(self):
		return self.reason if self.reason else 'دلیل ذکر نشده است.'

	def polymorphism(self):
		if SpecialPrivilegeRequest.objects.filter(pk=self.id).count():
			return SpecialPrivilegeRequest.objects.get(pk=self.id)
		return ReportAbuseRequest.objects.get(pk=self.id)

	def presentation(self):
		print("## parent polymorphisem:")
		return self.polymorphism().presentation()

	def deny(self):
		print("## parent polymorphisem:")
		return self.polymorphism().deny()
	def permit(self):
		print("## parent polymorphisem:")
		return self.polymorphism().permit()


class SpecialPrivilegeRequest(KRequest):
	neededPrivilege = models.IntegerField()

	def __str__(self):
		return 'SpecialPrivilegeRequest: ' + self.user.user.username + ' privilege:' + str(self.neededPrivilege)
	def presentation(self):
		return 'افزایش دسترسی به ' + str(self.neededPrivilege)

	def deny(self):
		self.state = 2
		print("---- SpecialPrivilegeRequest deny:")
		self.save()

	def permit(self):
		self.state = 1
		self.user.privilege = self.neededPrivilege
		self.user.save()
		print("---- SpecialPrivilegeRequest permit:")
		self.save()



class ReportAbuseRequest(KRequest):
	abusedName = models.CharField(max_length=255)
	REF_CHOICES = ((0, 'knowledge'),(1, 'tag'),(2, 'relation'),)
	ref = models.SmallIntegerField(choices=REF_CHOICES)
	remove_id = models.IntegerField()

	def __str__(self):
		return 'ReportAbuseRequest: ' + self.abusedName
	def presentation(self):
		return 'استفاده نادرست از' + self.abusedName

	def deny(self):
		self.state = 2
		print("---- ReportAbuseRequest deny:")
		self.save()

	def permit(self):
		self.state = 1
		if self.ref == 0:
			knowledge.models.Knowledge.kdelete(self.remove_id)
		if self.ref == 1:
			knowledge.models.Tag.kdelete(self.remove_id)
		if self.ref == 2:
			knowledge.models.InterknowledgeRelationship.kdelete(self.remove_id)
		print("---- ReportAbuseRequest permit:")
		self.save()

users/forms.py
__author__ = 'kasra'

import users.models
from knowledge.forms import convertFormErrorToFarsi

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class KUserForm(forms.ModelForm):

	# user = models.OneToOneField(User) mail,username,pass1,pass2,
	# state = models.IntegerField()
	email = forms.EmailField(label="میل")
	username = forms.RegexField(label="نام کاربری", max_length=30, regex=r'^[\w.@+-]+$', error_messages={'invalid': "This value may contain only letters, numbers and @/./+/-/_ characters."})
	pass1 = forms.CharField(label='رمز عبور', widget=forms.PasswordInput)
	pass2 = forms.CharField(label='تکرار رمز عبور', widget=forms.PasswordInput)

	def clean_pass2(self):
		data = self.cleaned_data['pass2']
		if data != self.cleaned_data['pass1']:
			raise forms.ValidationError('رمز عبور تطابق ندارد.', 'not matched')
		return data

	def clean_username(self):
		data = self.cleaned_data['username']
		if User.objects.filter(username=self.cleaned_data['username']).count() :
			raise forms.ValidationError('نام کاربری موجود است. لطفا نام دیگری انتخاب کنید.', 'duplicate')
		return data

	class Meta:
		model = users.models.KUser
		fields = ['realName', 'job', 'privilege', 'employeeId', 'isManager', 'gender']
		labels = {
			'realName': 'نام',
			'job': 'شغل',
			'privilege': 'سطح دسترسی',
			'employeeId': 'شماره ی کارمندی',
			'isManager': 'رتبه',
			'gender': 'جنسیت'
		}

	def __init__(self, *args, **kwargs):
		super(KUserForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)

	def save(self, commit=True):
		"""
			this method always save django user
		"""
		print('save django.user ')
		print(self.cleaned_data)
		usr = User.objects.create_user(self.cleaned_data['username'], self.cleaned_data['email'], self.cleaned_data['pass1'])
		kuser = users.models.KUser()
		kuser.user = usr
		kuser.realName = self.cleaned_data['realName']
		kuser.job = self.cleaned_data['job']
		kuser.privilege = self.cleaned_data['privilege']
		kuser.employeeId = self.cleaned_data['employeeId']
		kuser.isManager = self.cleaned_data['isManager']
		kuser.gender = self.cleaned_data['gender']
		print('create kuser:')
		print(kuser)

		if commit:
			kuser.save()
		return kuser



class SpecialPrivilegeForm(forms.ModelForm):
	class Meta:
		model = users.models.SpecialPrivilegeRequest
		fields = ['neededPrivilege', 'reason']
		labels = {
			'neededPrivilege': 'دسترسی مورد نیاز',
			'reason': 'دلیل',
		}

	def __init__(self, *args, **kwargs):
		super(SpecialPrivilegeForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)


class ChangePassForm(forms.Form):
	old_pass = forms.CharField(label='رمز عبور قدیمی', widget=forms.PasswordInput)
	pass1 = forms.CharField(label='رمز عبور جدید', widget=forms.PasswordInput)
	pass2 = forms.CharField(label='تکرار رمز عبور جدید', widget=forms.PasswordInput)

	def clean_pass2(self):
		data = self.cleaned_data['pass2']
		if data != self.cleaned_data['pass1']:
			raise forms.ValidationError('رمز عبور تطابق ندارد.', 'not matched')
		return data

	def clean_old_pass(self):
		data = self.cleaned_data['old_pass']
		if not authenticate(username=self.username, password=data):
			raise forms.ValidationError('رمز عبور اشتباه است.', 'wrong-pass')
		return data

	def __init__(self, *args, **kwargs):
		self.username = kwargs.pop('username', None)
		print('add username to change pass: ' + str(self.username))
		super(ChangePassForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)

users/templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head lang="en">
	<meta charset="UTF-8">
	<title></title>
	<style>
		@import url(http://weloveiconfonts.com/api/?family=entypo);
		@import url(http://fonts.googleapis.com/css?family=Roboto);
		/* zocial */
		[class*="entypo-"]:before {
			font-family: 'entypo', sans-serif;
		}

		*,*:before,*:after {
		-moz-box-sizing: border-box;
		-webkit-box-sizing: border-box;
		box-sizing: border-box;
		}

		h2 {
			color:rgba(255,255,255,.8);
			margin-left:12px;
		}

		body {
			background: rgb(138,213,240);
			font-family: 'Roboto', sans-serif;
		}

		form {
			position:relative;
			margin: 50px auto;
			width: 380px;
			height: auto;
		}

		input {
			padding: 16px;
			border-radius:7px;
			border:0px;
			background: rgba(255,255,255,.2);
			display: block;
			margin: 15px;
			width: 300px;
			color:white;
			font-size:18px;
			height: 54px;
		}

		input:focus {
			outline-color: rgba(0,0,0,0);
			background: rgba(255,255,255,.95);
			color: #33b5e5;
		}

		button {
			float:right;
			height: 121px;
			width: 50px;
			border: 0px;
			background: #33b5e5;
			border-radius:7px;
			padding: 10px;
			color:white;
			font-size:22px;
		}

		.inputUserIcon {
			position:absolute;
			top:68px;
			right: 80px;
			color:white;
		}

		.inputPassIcon {
			position:absolute;
			top:136px;
			right: 80px;
			color:white;
		}

		input::-webkit-input-placeholder {
			color: white;
		}

		input:focus::-webkit-input-placeholder {
			color: #33b5e5;
		}
		#error-message{
			color: red;
			margin-left: 20px;
		}


	</style>
</head>
<body>

	<form method="post" action="">
		<h2><span class="entypo-login"></span> ورود</h2>
		<button class="submit"><span class="entypo-lock"></span></button>
		<span class="entypo-user inputUserIcon"></span>
		<input name="username" type="text" class="user" placeholder="نام کاربری"/>
		<span class="entypo-key inputPassIcon"></span>
		<input name="password" type="password" class="pass" placeholder="رمز عبور"/>
		{% if invalidLogin %}
			<div id="error-message">{{ errorMessage }}</div>
		{% endif %}
	</form>


	<script src={% static "js/jquery-2.1.4.min.js"%}></script>
	<script>
		$(".user").focusin(function(){
			$(".inputUserIcon").css("color", "#33b5e5");
			}).focusout(function(){
				$(".inputUserIcon").css("color", "white");
			});

		$(".pass").focusin(function(){
			$(".inputPassIcon").css("color", "#33b5e5");
			}).focusout(function(){
				$(".inputPassIcon").css("color", "white");
			});
	</script>
</body>
</html>

users/templates/user/register.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form method="post" action="">
		<h2 class="h-title" dir="rtl">ثبت نام کاربر</h2>

		<div class="form-container">
			<!-- username -->
			<p><label for="{{ form.username.id_for_label }}">{{ form.username.label }}*</label></p>
			<p>{{ form.username|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.username.errors }}</div>

			<!-- realName -->
			<p><label for="{{ form.realName.id_for_label }}">{{ form.realName.label }}*</label></p>
			<p>{{ form.realName|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.realName.errors }}</div>

			<!-- gender -->
			<p><label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}*</label></p>
			<p>{{ form.gender|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.gender.errors }}</div>

			<!-- email -->
			<p><label for="{{ form.email.id_for_label }}">{{ form.email.label }}*</label></p>
			<p>{{ form.email|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.email.errors }}</div>

			<!-- employeeId -->
			<p><label for="{{ form.employeeId.id_for_label }}">{{ form.employeeId.label }}*</label></p>
			<p>{{ form.employeeId|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.employeeId.errors }}</div>

			<!-- job -->
			<p><label for="{{ form.job.id_for_label }}">{{ form.job.label }}*</label></p>
			<p>{{ form.job|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.job.errors }}</div>

			<!-- isManager -->
			<p><label for="{{ form.isManager.id_for_label }}">{{ form.isManager.label }}*</label></p>
			<p>{{ form.isManager|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.isManager.errors }}</div>

			<!-- privilege -->
			<p><label for="{{ form.privilege.id_for_label }}">{{ form.privilege.label }}*</label></p>
			<p>{{ form.privilege|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.privilege.errors }}</div>

			<!-- pass1 -->
			<p><label for="{{ form.pass1.id_for_label }}">{{ form.pass1.label }}*</label></p>
			<p>{{ form.pass1|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.pass1.errors }}</div>

			<!-- pass2 -->
			<p><label for="{{ form.pass2.id_for_label }}">{{ form.pass2.label }}*</label></p>
			<p>{{ form.pass2|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.pass2.errors }}</div>

			<div class="small margin-bottom-15">پر کردن ورودی هایی که با * مشخص شده اند ضروریست.</div>

			{% if success %}
				<div class="form-success">کاربر با موفقیت ساخته شد.</div>
			{% endif %}
			<p class=""><input type='submit' class="btn btn-info" value="ایجاد"></p>
		</div>
		


	</form>
{% endblock %}

users/templates/user/report-user-activity-result.html
{% load humanize %}
<div class="">
    <h2 class="h-title" dir="rtl">فعالیت کاربران</h2>
    <table class="k-table simple-part-margin">
        <tr>
            <th style="width: 15%;">نام کاربری</th>
            <th style="width: 70%;">فعالیت</th>
            <th style="width: 15%;">تارخ</th>
        </tr>
        {% for log in logs %}
            <tr>
                <td style="width: 15%;">{{ log.user.user.username }}</td>
                <td style="width: 70%;">{{ log.detail }}</td>
                <td style="width: 15%;"><span dir="ltr">{{ log.createDate|naturaltime }}</span></td>
            </tr>
        {% endfor %}
    </table>
</div>

users/templates/user/search-user.html
{% extends 'base.html' %}

{% block content %}
	<h2 class="h-title" dir="rtl">جستجو : کاربر</h2>
	<form method="get" action="{% url 'show-search-user' %}">
		<div class="form-container">
			<!-- name -->
			<p><label for="id_name">نام</label></p>
			<p><input class="form-input" id="id_name" maxlength="255" name="name" type="text"></p>

			<!-- username -->
			<p><label for="id_username">نام کاربری</label></p>
			<p><input class="form-input" id="id_username" maxlength="255" name="username" type="text"></p>

			<p ><input type='submit' class="btn btn-info" value="جستجو"	></p>
		</div>
	</form>
	<hr class="content-divider"/>

	{% for usr in kusers %}
		{% include 'user/util/single-user-profile.html' with kuser=usr folded=True %}
	{% endfor %}


{% endblock %}

users/templates/user/show-change-password.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form method="post" action="">
		<h2 class="h-title" dir="rtl">تغییر رمز</h2>

		<div class="form-container">
			<!-- username -->
			<p><label for="{{ form.old_pass.id_for_label }}">{{ form.old_pass.label }}*</label></p>
			<p>{{ form.old_pass|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.old_pass.errors }}</div>

			<!-- pass1 -->
			<p><label for="{{ form.pass1.id_for_label }}">{{ form.pass1.label }}*</label></p>
			<p>{{ form.pass1|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.pass1.errors }}</div>

			<!-- pass2 -->
			<p><label for="{{ form.pass2.id_for_label }}">{{ form.pass2.label }}*</label></p>
			<p>{{ form.pass2|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.pass2.errors }}</div>

			<div class="small margin-bottom-15">پر کردن ورودی هایی که با * مشخص شده اند ضروریست.</div>

			{% if success %}
				<div class="form-success">رمز عبور با موفقیت تغییر یافت.</div>
			{% endif %}
			<p class=""><input type='submit' class="btn btn-info" value="تغییر"></p>
		</div>



	</form>
{% endblock %}

users/templates/user/show-dismiss-user.html
{% extends 'base.html' %}

{% block content %}
	<div class="">
		<h2 class="h-title" dir="rtl">اخراج کاربر</h2>
		<div id="dismiss-submit-message"></div>
		<table class="k-table table-selectable simple-part-margin">
			<tr>
				<th>نام کاربری</th>
				<th>نام</th>
				<th>شماره کارمندی</th>
				<th>شغل</th>
				<th>سطح دسترسی</th>
				<th>وضعیت</th>
			</tr>
			{% for kuser in kusers %}
				<tr data-kuser-id="{{ kuser.id }}">
					<td>{{ kuser.user.username }}</td>
					<td>{{ kuser.realName }}</td>
					<td>{{ kuser.employeeId }}</td>
					<td>{{ kuser.job }}</td>
					<td>{{ kuser.privilege }}</td>
					<td>{{ kuser.get_state_display }}</td>
				</tr>
			{% endfor %}
		</table>
		<button id="dismiss-but" type='submit' class="btn btn-info center-block text-center ">اخراج</button>
	</div>

{% endblock %}

{% block additional-script %}
	<script>
		$('#dismiss-but').on('click', function(e){
			console.log('dismiss');
			var ids = [];
			$('tr.selected-row').each(function(idx, elem){
				console.log('add element');
				console.log(elem);
				ids.push($(elem).attr('data-kuser-id'));
			});
			console.log('ids:');
			console.log(ids);
			$.post("{% url 'dismiss' %}", {'ids': JSON.stringify(ids)}, function(data){
				console.log('receive dismiss response');
				console.log(data);
				$('#dismiss-submit-message').html(data['message']);
				if(data['success']) {
					setTimeout(function(){
						console.log('reload page');
						location.reload();
					}, 5000);
				}

			});
		});

	</script>
{% endblock %}

users/templates/user/show-report-user-activity.html
{% extends 'base.html' %}

{% block content %}
	<div class="">
		<h2 class="h-title" dir="rtl">گزارش فعالیت کاربران</h2>
		<div id="choose-submit-message"></div>
		<table class="k-table table-selectable simple-part-margin">
			<tr>
				<th>نام کاربری</th>
				<th>نام</th>
				<th>شماره کارمندی</th>
				<th>شغل</th>
				<th>سطح دسترسی</th>
				<th>وضعیت</th>
			</tr>
			{% for kuser in kusers %}
				<tr data-kuser-id="{{ kuser.id }}">
					<td>{{ kuser.user.username }}</td>
					<td>{{ kuser.realName }}</td>
					<td>{{ kuser.employeeId }}</td>
					<td>{{ kuser.job }}</td>
					<td>{{ kuser.privilege }}</td>
					<td>{{ kuser.get_state_display }}</td>
				</tr>
			{% endfor %}
		</table>
		<button id="choose-but" type='submit' class="btn btn-info center-block text-center ">انتخاب</button>
	</div>

    <div id="report-result"></div>

{% endblock %}

{% block additional-script %}
	<script>
		$('#choose-but').on('click', function(e){
			console.log('report');
			var ids = [];
			$('tr.selected-row').each(function(idx, elem){
				console.log('add element');
				console.log(elem);
				ids.push($(elem).attr('data-kuser-id'));
			});
			console.log('ids:');
			console.log(ids);
			$.post("{% url 'show-report-user-activity' %}", {'ids': JSON.stringify(ids)}, function(data){
				console.log('receive report response');
				console.log(data);
				if(data['success']){
                   $('#report-result').html(data['result']);
                }
			});
		});

	</script>
{% endblock %}