OOD_Project/urls.py
import users.urls
import knowledge.urls

from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$',  RedirectView.as_view(pattern_name='base-view', permanent=True)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include(users.urls)),
    url(r'^knowledge/', include(knowledge.urls)),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knowledge/urls.py
__author__ = 'kasra'

import knowledge.views

from django.conf.urls import include, url


def emptyFunc():
    pass

urlpatterns = [
    url(r'^source/add/$', knowledge.views.showAddSource, name='add-source'),
    url(r'^knowledge/add/$', knowledge.views.showAddKnowledge, name='add-knowledge'),
    url(r'^tag-type/add/$', knowledge.views.showAddTagType, name='add-tag-type'),
    url(r'^relation-type/add/$', knowledge.views.showAddRelationType, name='add-relation-type'),
    url(r'^tag/remove/$', knowledge.views.removeTagAj, name='remove-tag'),
    url(r'^relation/remove/$', knowledge.views.removeRelationAj, name='remove-relation'),
    url(r'^knowledge/remove/$', knowledge.views.removeKnowledgeAj, name='remove-knowledge'),
    url(r'^knowledge/(?P<knowledge_id>\d+)/$', knowledge.views.showKnowledge, name='show-knowledge'),
    url(r'^knowledge/(?P<knowledge_id>\d+)/edit$', knowledge.views.showEditKnowledge, name='edit-knowledge'),
    url(r'^knowledge/(?P<knowledge_id>\d+)/rate', knowledge.views.rateKnowledgeAJ, name='rate-knowledge'),
    url(r'^knowledge/(?P<knowledge_id>\d+)/add-relation/$', knowledge.views.addRelationAJ, name='add-relation-knowledge'),
    url(r'^knowledge/(?P<knowledge_id>\d+)/add-tag/$', knowledge.views.addTagAJ, name='add-tag-knowledge'),
    url(r'^knowledge/(?P<knowledge_id>\d+)/add-comment/$', knowledge.views.addCommentAJ, name='add-comment-knowledge'),
    url(r'^source/(?P<source_id>\d+)/$', knowledge.views.showSource, name='show-source'),

    url(r'^search/knowledge/$', knowledge.views.showSearchKnowledge, name='show-search-knowledge'),
    url(r'^search/source/$', knowledge.views.showSearchSource, name='show-search-source'),
    url(r'^report-abuse/$', knowledge.views.reportAbuseAj, name='report-abuse'),



]

users/urls.py
from django.conf.urls import url
import users.views

urlpatterns = [
    url(r'^login/$', users.views.loginView, name='login'),
    url(r'^logout/$', users.views.logoutAj, name='logout'),
    url(r'^base/$', users.views.baseView, name='base-view'),
    url(r'^register/$', users.views.showRegisterKUser, name='register'),
    url(r'^dismiss/$', users.views.showDismissKUser, name='dismiss'),
    url(r'^change-pass/$', users.views.showChangePass, name='change-pass'),
    url(r'^report-user-activity/$', users.views.showReportUserActivity, name='show-report-user-activity'),
    url(r'^special-privilege-request/$', users.views.showSpecialprivilageRequest, name='show-special-privilege-request'),
    url(r'^request-manager/$', users.views.showRequestManager, name='show-request-manager'),
    url(r'^user-profile/(?P<user_id>\d+)$', users.views.userProfileView, name='show-user-profile'),

    url(r'^search/user/$', users.views.searchUser, name='show-search-user'),
]

knowledge/models.py
from datetime import datetime
import users.models

from django.db import models



def knowledge_file_name(instance, filename):
	return '/'.join(['file', instance.author.user.username, filename])

###################  knowledge  ###################
class Knowledge(models.Model):
	subject = models.CharField(max_length=255)
	source = models.ForeignKey('Source', related_name='knowledge')
	author = models.ForeignKey('users.KUser', related_name='knowledge')
	summary = models.CharField(max_length=255, blank=True, null=True)
	gainWay = models.TextField(blank=True, null=True)
	access = models.IntegerField(default=0)
	createDate = models.DateTimeField(default=datetime.now)

	content = models.TextField(blank=True, null=True)
	file = models.FileField(blank=True, null=True, upload_to=knowledge_file_name)

	def __str__(self):
		return '' + self.subject

	def presentation(self):
		return self.subject

	def rate(self, kuser, vote):
		try:
			rate = Rate.objects.get(knowledge=self, voter=kuser)
		except:
			rate = Rate()
			rate.knowledge = self
			rate.voter = kuser
		rate.up = vote
		rate.save()

	@staticmethod
	def kdelete(id):
		print('remove knowledge :' + repr(id))
		Knowledge.objects.filter(pk=id).delete()


class Rate(models.Model):
	up = models.BooleanField(default=True)
	voter = models.ForeignKey('users.KUser', related_name='rates')
	knowledge = models.ForeignKey('Knowledge', related_name='rates')

	class Meta:
		unique_together = ['voter', 'knowledge']

	def __str__(self):
		return str(self.knowledge) + ' vote ' + ('up' if self.up else 'down') + ' by ' + str(self.voter)


###################  Source  ###################
class Source(models.Model):
	subject = models.CharField(max_length=255, unique=True)
	description = models.TextField()
	createDate = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return self.subject

	def presentation(self):
		return self.subject


class ProjectProces(Source):
	phase = models.CharField(max_length=255)
	startDate = models.DateTimeField()
	endDate = models.DateTimeField()

	def __str__(self):
		return 'ProjectProces: ' + self.phase + '.' + self.subject
		

###################  Tag  ###################
class TagType(models.Model):
	name = models.CharField(max_length=255, unique=True,error_messages={'unique':'نوع برچسب برای این مبحث موجود است.'})

	def __str__(self):
		return '' + self.name

	def presentation(self):
		return self.name


class Tag(models.Model):
	ktype = models.ForeignKey('TagType', related_name='tags')
	knowledge = models.ForeignKey('Knowledge', related_name='tags')

	class Meta:
		unique_together = ['ktype', 'knowledge']

	def __str__(self):
		return 'Tag: (' + self.ktype.name + ') -> ' + self.knowledge.subject

	def abuse_presentation(self):
		return 'برچسب: ' + self.ktype.name + '-' + self.knowledge.subject

	@staticmethod
	def kdelete(id):
		print('remove tag :' + repr(id))
		Tag.objects.filter(pk=id).delete()



###################  Relation  ###################
class InterknowledgeRelationshipType(models.Model):
	name = models.CharField(max_length=255, unique=True,error_messages={'unique':'نوع رابطه برای این مبحث موجود است.'})

	def __str__(self):
		return '' + self.name

	def presentation(self):
		return self.name


class InterknowledgeRelationship(models.Model):
	ktype = models.ForeignKey('InterknowledgeRelationshipType', related_name='relations')
	fromKnowledge = models.ForeignKey('Knowledge', related_name='relationToKnowledge')
	toKnowledge = models.ForeignKey('Knowledge', related_name='relationFromKnowledge')

	class Meta:
		unique_together = ['ktype', 'fromKnowledge', 'toKnowledge']

	def __str__(self):
		return 'InterknowledgeRelationship: (' +self.ktype.name + '( '\
		       + self.fromKnowledge.subject + ' -> ' + self.toKnowledge.subject + ' )'

	def abuse_presentation(self):
		return 'رابطه: ' + self.ktype.name + ' از ' + self.fromKnowledge.subject + ' به ' + self.toKnowledge.subject

	@staticmethod
	def kdelete(id):
		print('remove relation :' + repr(id))
		InterknowledgeRelationship.objects.filter(pk=id).delete()



###################  comment  ###################
class Comment(models.Model):
	author = models.ForeignKey('users.KUser', related_name='comments')
	knowledge = models.ForeignKey('Knowledge', related_name='comments')
	text = models.TextField()
	date = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return 'comment: ' + self.author.user.username + ' on ' + self.knowledge.subject


class KnowledgeUsage(models.Model):
	projectProces = models.ForeignKey('ProjectProces', related_name='usedIn')

	def __str__(self):
		return 'knowledge use: ' + self.author.user.username + ' used ' + self.knowledge.subject + ' in ' + self.projectProces.phase


###################  letter  ###################
# class Letter(models.Model):
# 	subject = models.CharField(max_length=255)
# 	sender = models.CharField(max_length=255)
# 	reciver = models.CharField(max_length=255)
# 	text = models.TextField()
# 	date = models.DateTimeField()

# 	def __str__(self):
# 		return 'letter: ' + self.subject + ' from ' + self.sender + ' to ' + self.reciver

knowledge/forms.py
__author__ = 'kasra'

import knowledge.models

from django import forms


def convertFormErrorToFarsi(form):
	for field in form.fields.values():
		field.error_messages = {'required':('پر کردن ' + '"{fieldname}"' + ' ضروری است.').
		format(fieldname=field.label),
		'invalid':('اطلاعات ' + '"{fieldname}"' + ' صحیح نیست.').format(fieldname=field.label),
		}


class SourceForm(forms.ModelForm):
	class Meta:
		model = knowledge.models.Source
		fields = ['subject', 'description']
		labels = {
			'subject': 'موضوع',
			'description': 'شرح'
		}

	def __init__(self, *args, **kwargs):
		super(SourceForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)




class InterKnowledgeRelationshipForm(forms.ModelForm):
	class Meta:
		model = knowledge.models.InterknowledgeRelationship
		fields = ['ktype', 'fromKnowledge', 'toKnowledge']
		labels = {
			'ktype': 'نوع',
			'fromKnowledge': 'از',
			'toKnowledge': 'به'
		}

	def __init__(self, *args, **kwargs):
		super(InterKnowledgeRelationshipForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)



class TagForm(forms.ModelForm):
	class Meta:
		model = knowledge.models.Tag
		fields = ['ktype']
		labels = {
			'ktype': 'نوع',
		}

	def __init__(self, *args, **kwargs):
		super(TagForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)


class KnowledgeForm(forms.ModelForm):
	class Meta:
		model = knowledge.models.Knowledge
		fields = ['subject', 'source', 'content', 'summary', 'gainWay', 'access', 'file']
		exclude = ['author']
		labels = {
			'subject': 'موضوع',
			'source': 'منبع',
			'content': 'محتوا',
			'summary':'خلاصه',
			'gainWay':'طریقه ی کسب',
			'access':'دسترسی',
			'file':'فایل',
		}

	def __init__(self, *args, **kwargs):
		super(KnowledgeForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)



class RelationTypeForm(forms.ModelForm):
	class Meta:
		model = knowledge.models.InterknowledgeRelationshipType
		fields = ['name']
		labels = {
			'name': 'مبحث',
		}

	def __init__(self, *args, **kwargs):
		super(RelationTypeForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)

class TagTypeForm(forms.ModelForm):
	class Meta:
		model = knowledge.models.TagType
		fields = ['name']
		labels = {
			'name': 'مبحث',
		}

	def __init__(self, *args, **kwargs):
		super(TagTypeForm, self).__init__(*args, **kwargs)
		convertFormErrorToFarsi(self)

knowledge/templates/knowledge/add-knowledge.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form method="post" action="" enctype="multipart/form-data">
		<h2 class="h-title" dir="rtl">{{ action }}: دانش</h2>

		<div class="form-container">
			<!-- subject -->
			<p><label for="{{ form.subject.id_for_label }}">{{ form.subject.label }}*</label></p>
			<p>{{ form.subject|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.subject.errors }}</div>

			<!-- source -->
			<p><label for="{{ form.source.id_for_label }}">{{ form.source.label }}*</label></p>
			<p>{{ form.source|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.source.errors }}</div>

			<!-- summary -->
			<p><label for="{{ form.summary.id_for_label }}">{{ form.summary.label }}</label></p>
			<p>{{ form.summary|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.summary.errors }}</div>

			<!-- content -->
			<p><label for="{{ form.content.id_for_label }}">{{ form.content.label }}</label></p>
			<p>{{ form.content|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.content.errors }}</div>

			<!-- file -->
{#			<p>{{ form.file }}</p>#}
			<p><label for="{{ form.file.id_for_label }}">{{ form.file.label }}</label></p>
			<p>{{ form.file|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.file.errors }}</div>

			<!-- gainWay -->
			<p><label for="{{ form.gainWay.id_for_label }}">{{ form.gainWay.label }}</label></p>
			<p>{{ form.gainWay|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.gainWay.errors }}</div>

			<!-- access -->
			<p><label for="{{ form.access.id_for_label }}">{{ form.access.label }}*</label></p>
			<p>{{ form.access|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.access.errors }}</div>

			<div class="small margin-bottom-15">پر کردن ورودی هایی که با * مشخص شده اند ضروریست.</div>

			{% if success %}
				<div class="form-success">{{ action }} با موفقیت انجام شد.</div>
			{% endif %}
			<p class=""><input type='submit' class="btn btn-info" value="{{ action }}"></p>
		</div>
		


	</form>
{% endblock %}

knowledge/templates/knowledge/add-relation-type.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form method="post" action="">
		<h2 class="h-title" dir="rtl">ایجاد: نوع رابطه</h2>

		<div class="form-container">
			<!-- name -->
			<p><label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label></p>
			<p>{{ form.name|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.name.errors }}</div>

			<div class="small margin-bottom-15">پر کردن ورودی هایی که با * مشخص شده اند ضروریست.</div>

			{% if success %}
				<div class="form-success">نوع رابطه با موفقیت ثبت شد.</div>
			{% endif %}
			<p class=""><input type='submit' class="btn btn-info" value="ایجاد"></p>
		</div>



	</form>
{% endblock %}

knowledge/templates/knowledge/add-source.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form method="post" action="">
		<h2 class="h-title" dir="rtl">ایجاد: منبع</h2>
		<!-- <table class="table-form" dir="rtl"> -->
			<!-- {{ addSourceForm.as_table}} -->
			<!-- <tr class="center-element">
				<input type='submit' class="btn btn-info">
			</tr> -->
		<!-- </table> -->
<!-- <input type='submit' class="btn btn-info"> -->

		<div class="form-container">
			<p><label for="id_subject">موضوع</label></p>
			<p>{{ form.subject|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.subject.errors }}</div>
			<p><label for="id_description">شرح</label></p>
			<p>{{ form.description|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.description.errors }}</div>
			<!-- <div class="form-error">{{ addSourceForm.errors }}</div> -->

			<div class="small margin-bottom-15">پر کردن ورودی هایی که با * مشخص شده اند ضروریست.</div>

			{% if success %}
				<div class="form-success">منبع با موفقیت ثبت شد.</div>
			{% endif %}
			<p class=""><input type='submit' class="btn btn-info" value="افزودن"></p>
		</div>
		

		<!-- <div class="form-container">
			<p><label for="id_subject">موضوع</label></p>
			<p><input id="id_subject" class="form-control" maxlength="255" name="subject" type="text"></p>
			<p>{{ addSourceForm.error }}</p>
			<p><label for="id_description">شرح</label></p>
			<p><textarea cols="40" id="id_description" class="form-control" name="description" rows="10"></textarea></p>
			<p>{{ addSourceForm.error }}</p>
			<p class="center-element"><input type='submit' class="btn btn-info"></p>
		</div> -->

{#		<div class="form-group">#}
{#			<label for="id_subject">موضوع</label>#}
{#			<input id="id_subject" class="form-control" maxlength="255" name="subject" type="text">#}
{#		</div>#}
{#		<div class="form-group">#}
{#			<label for="id_description">شرح</label>#}
{#			<textarea cols="40" id="id_description" name="description" rows="10"></textarea>#}
{#		</div>#}

	</form>
{% endblock %}

knowledge/templates/knowledge/add-tag-type.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form method="post" action="">
		<h2 class="h-title" dir="rtl">ایجاد: برچسب</h2>

		<div class="form-container">
			<!-- name -->
			<p><label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label></p>
			<p>{{ form.name|add_class:'form-input' }}</p>
			<div class="form-error">{{ form.name.errors }}</div>


			<div class="small margin-bottom-15">پر کردن ورودی هایی که با * مشخص شده اند ضروریست.</div>

			{% if success %}
				<div class="form-success">نوع برچسب با موفقیت ثبت شد.</div>
			{% endif %}
			<p class=""><input type='submit' class="btn btn-info" value="ایجاد"></p>
		</div>



	</form>
{% endblock %}

knowledge/templates/knowledge/search-knowledge.html
{% extends 'base.html' %}

{% block content %}
	<h2 class="h-title" dir="rtl">جستجو : دانش</h2>
	<form method="get" action="{% url 'show-search-knowledge' %}">
		<div class="form-container">
			<!-- subject -->
			<p><label for="id_subject">موضوع</label></p>
			<p><input class="form-input" id="id_subject" maxlength="255" name="subject" type="text"></p>

			<!-- source -->
			<p><label for="id_source_subject">موضوع منبع</label></p>
			<p><input class="form-input" id="id_source_subject" maxlength="255" name="source_subject" type="text"></p>

			<p ><input type='submit' class="btn btn-info" value="جستجو"></p>
		</div>
	</form>
	<hr class="content-divider"/>

	{% for kn in knowledge %}
		{% include 'knowledge/util/folded-single-knowledge.html' with knowledge=kn %}
	{% endfor %}


{% endblock %}

knowledge/templates/knowledge/search-source.html
{% extends 'base.html' %}

{% block content %}
	<h2 class="h-title" dir="rtl">جستجو : منبع</h2>
	<form method="get" action="{% url 'show-search-source' %}">
		<div class="form-container">
			<!-- subject -->
			<p><label for="id_subject">موضوع</label></p>
			<p><input class="form-input" id="id_subject" maxlength="255" name="subject" type="text"></p>

			<p ><input type='submit' class="btn btn-info" value="جستجو"></p>
		</div>
	</form>
	<hr class="content-divider"/>

	{% for src in sources %}
		{% include 'knowledge/util/folded-single-source.html' with source=src %}
	{% endfor %}


{% endblock %}

knowledge/templates/knowledge/show-knowledge.html
{% extends 'base.html' %}

{% block content %}


{% include 'knowledge/util/add-relation.html' %}
{% include 'knowledge/util/add-tag.html' %}
{% include 'knowledge/util/abuse-reason.html' %}
{% include 'knowledge/util/expanded-single-knowledge.html' %}


{% endblock %}

knowledge/templates/knowledge/show-source.html
{% extends 'base.html' %}

{% block content %}


	<div class="source single-block">
		<div class="source-subject">
			<h1>{{ source.subject }}</h1>
		</div>

		<hr class='block-part-divider'>
		<div class="source-description">
			<h2>شرح:</h2>
			<p>{{ source.description }}</p>
		</div>
	</div>

	<hr class="content-divider"/>

	<h1 class="title">دانش ها:</h1>
	{% for kn in source.knowledge.all %}
		{% include 'knowledge/util/folded-single-knowledge.html' with knowledge=kn %}
	{% endfor %}

{% endblock %}